#!/bin/sh
#
# Start SNAPcom
#

start() {
	echo -n "Starting tm_sender "
    start-stop-daemon -S -b -x /usr/bin/python /root/tm_sender.py
	echo "done"
}
stop() {
	echo "done"
}
restart() {
	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

